### ISSUE TITLE
Duplication in 1.21.1 on Purpur server

### ISSUE THREAD

**Issue by Canz2** [BT-Pluginz/GravePlugin#4]
My friend got a duplication bug with the grave.

When he was heading to his stuff, his inventory was full
and he tried to get his stuff, but the head never disappear so he can get unlimited copy of his stuff

When I check the log of the server I see this error

```
[20:08:48] [Server thread/WARN]: [BTGraves] Task #1320 for BTGraves v1.0 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.ArmorStand.setCustomName(String)" because "armorStand" is null
	at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.updateGraveName(GraveTimeoutManager.java:104) ~[BT-Graves-v1.0.jar:?]
	at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.lambda$startGraveTimeoutTask$0(GraveTimeoutManager.java:86) ~[BT-Graves-v1.0.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

We tried multiple time to reproduce the bug but without any success

Here is the full info of the server
Version : Purpur-1.12.1-2295
Plugins list : BlueMap-5.3, BT-Graves-v1.0, Chunky-1.4.10, InvSee++, SkinsRestorer
Java version : JDK 21
with 8Gbs of RAM

I managed to delete the grave by getting in spectator mode to see the armor stand and killing it with command and break the head

**Comment by TubYoub** [comment]
So i could find the error which was associated with the error log you provided but i also couldnt reproduce the dupe you expierenced. If you could provide more context or maybe a full log so i can see if there is any other error?
[https://mclo.gs/](https://mclo.gs/)

**Comment by Canz2** [comment]
We tried to reproduce the bug and we finally managed to get it back
when a player get killed by the warden with the ray not a physical damage he gets the duplication bug
and he can only duplicate if he choose to retrieve the stuff not to drop it

**Comment by TubYoub** [comment]
soooo,
Can you see anything in the logs that might cause this error? because i stil cant reproduce this bug.
I am using the same paper build on a fresh server but only with the Grave Plugin and i also looked into the code again and nothing suggests that this has anything to do with the Grave Plugin.

**Comment by Canz2** [comment]
I tried to reproduce the bug 17 times but with no success

Here is a piece of the error I have in the console, I don't know how to get more info of it.
Do you know how I can enabled a verbose mode or something similar ?
```
847 | [20:08:58] [Server thread/WARN]: [BTGraves] Task #1320 for BTGraves v1.0 generated an exception
848 | java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.ArmorStand.setCustomName(String)" because "armorStand" is null
849 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.updateGraveName(GraveTimeoutManager.java:104) ~[BT-Graves-v1.0.jar:?]
850 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.lambda$startGraveTimeoutTask$0(GraveTimeoutManager.java:86) ~[BT-Graves-v1.0.jar:?]
851 | at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
852 | at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
853 | at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
854 | at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
855 | at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
856 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
857 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
858 | at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
859 | [20:08:59] [Server thread/WARN]: [BTGraves] Task #1320 for BTGraves v1.0 generated an exception
860 | java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.ArmorStand.setCustomName(String)" because "armorStand" is null
861 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.updateGraveName(GraveTimeoutManager.java:104) ~[BT-Graves-v1.0.jar:?]
862 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.lambda$startGraveTimeoutTask$0(GraveTimeoutManager.java:86) ~[BT-Graves-v1.0.jar:?]
863 | at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
864 | at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
865 | at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
866 | at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
867 | at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
868 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
869 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
870 | at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
871 | [20:09:00] [Server thread/WARN]: [BTGraves] Task #1320 for BTGraves v1.0 generated an exception
872 | java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.ArmorStand.setCustomName(String)" because "armorStand" is null
873 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.updateGraveName(GraveTimeoutManager.java:104) ~[BT-Graves-v1.0.jar:?]
874 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.lambda$startGraveTimeoutTask$0(GraveTimeoutManager.java:86) ~[BT-Graves-v1.0.jar:?]
875 | at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
876 | at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
877 | at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
878 | at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
879 | at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
880 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
881 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
882 | at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
883 | [20:09:01] [Server thread/WARN]: [BTGraves] Task #1320 for BTGraves v1.0 generated an exception
884 | java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.ArmorStand.setCustomName(String)" because "armorStand" is null
885 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.updateGraveName(GraveTimeoutManager.java:104) ~[BT-Graves-v1.0.jar:?]
886 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.lambda$startGraveTimeoutTask$0(GraveTimeoutManager.java:86) ~[BT-Graves-v1.0.jar:?]
887 | at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
888 | at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
889 | at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
890 | at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
891 | at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
892 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
893 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
894 | at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
895 | [20:09:02] [Server thread/WARN]: [BTGraves] Task #1320 for BTGraves v1.0 generated an exception
896 | java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.ArmorStand.setCustomName(String)" because "armorStand" is null
897 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.updateGraveName(GraveTimeoutManager.java:104) ~[BT-Graves-v1.0.jar:?]
898 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.lambda$startGraveTimeoutTask$0(GraveTimeoutManager.java:86) ~[BT-Graves-v1.0.jar:?]
899 | at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
900 | at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
901 | at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
902 | at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
903 | at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
904 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
905 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
906 | at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
907 | [20:09:03] [Server thread/WARN]: [BTGraves] Task #1320 for BTGraves v1.0 generated an exception
908 | java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.ArmorStand.setCustomName(String)" because "armorStand" is null
909 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.updateGraveName(GraveTimeoutManager.java:104) ~[BT-Graves-v1.0.jar:?]
910 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.lambda$startGraveTimeoutTask$0(GraveTimeoutManager.java:86) ~[BT-Graves-v1.0.jar:?]
911 | at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
912 | at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
913 | at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
914 | at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
915 | at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
916 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
917 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
918 | at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
919 | [20:09:04] [Server thread/WARN]: [BTGraves] Task #1320 for BTGraves v1.0 generated an exception
920 | java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.ArmorStand.setCustomName(String)" because "armorStand" is null
921 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.updateGraveName(GraveTimeoutManager.java:104) ~[BT-Graves-v1.0.jar:?]
922 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.lambda$startGraveTimeoutTask$0(GraveTimeoutManager.java:86) ~[BT-Graves-v1.0.jar:?]
923 | at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
924 | at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
925 | at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
926 | at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
927 | at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
928 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
929 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
930 | at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
931 | [20:09:05] [Server thread/WARN]: [BTGraves] Task #1320 for BTGraves v1.0 generated an exception
932 | java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.ArmorStand.setCustomName(String)" because "armorStand" is null
933 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.updateGraveName(GraveTimeoutManager.java:104) ~[BT-Graves-v1.0.jar:?]
934 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.lambda$startGraveTimeoutTask$0(GraveTimeoutManager.java:86) ~[BT-Graves-v1.0.jar:?]
935 | at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
936 | at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
937 | at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
938 | at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
939 | at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
940 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
941 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
942 | at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
943 | [20:09:06] [Server thread/WARN]: [BTGraves] Task #1320 for BTGraves v1.0 generated an exception
944 | java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.ArmorStand.setCustomName(String)" because "armorStand" is null
945 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.updateGraveName(GraveTimeoutManager.java:104) ~[BT-Graves-v1.0.jar:?]
946 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.lambda$startGraveTimeoutTask$0(GraveTimeoutManager.java:86) ~[BT-Graves-v1.0.jar:?]
947 | at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
948 | at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
949 | at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
950 | at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
951 | at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
952 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
953 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
954 | at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
955 | [20:09:07] [Server thread/WARN]: [BTGraves] Task #1320 for BTGraves v1.0 generated an exception
956 | java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.ArmorStand.setCustomName(String)" because "armorStand" is null
957 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.updateGraveName(GraveTimeoutManager.java:104) ~[BT-Graves-v1.0.jar:?]
958 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.lambda$startGraveTimeoutTask$0(GraveTimeoutManager.java:86) ~[BT-Graves-v1.0.jar:?]
959 | at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
960 | at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
961 | at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
962 | at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
963 | at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
964 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
965 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
966 | at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
967 | [20:09:08] [Server thread/WARN]: [BTGraves] Task #1320 for BTGraves v1.0 generated an exception
968 | java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.ArmorStand.setCustomName(String)" because "armorStand" is null
969 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.updateGraveName(GraveTimeoutManager.java:104) ~[BT-Graves-v1.0.jar:?]
970 | at BT-Graves-v1.0.jar/dev.pluginz.graveplugin.manager.GraveTimeoutManager.lambda$startGraveTimeoutTask$0(GraveTimeoutManager.java:86) ~[BT-Graves-v1.0.jar:?]
971 | at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
972 | at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
973 | at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
974 | at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
975 | at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
976 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
977 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
978 | at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by TubYoub** [comment]
The error you provided is not relevant cause it just says that it cant update the Name of an alr removed armor stand, i alr fixed that and will do an update so this dupe bug is from my standpoint not from my Plugin.
